# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-03 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_auto_20170630_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='escritor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
