# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-05 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_auto_20170703_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='slug',
            field=models.SlugField(default=2, editable=False),
            preserve_default=False,
        ),
    ]
