# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-17 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0006_auto_20170711_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ayuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregunta', models.CharField(blank=True, max_length=500, null=True)),
                ('R_pregunta', models.TextField(blank=True, max_length=9000000, null=True)),
                ('subida', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
