# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-11 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_gru_o_art', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_musi', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(choices=[('', '----'), ('Alternativa', 'Alternativa'), ('Balada', 'Balada'), ('Balada POP', 'Balada POP'), ('Blues', 'Blues'), ('Country', 'Country'), ('Death Metal', 'Death Metal'), ('Electr\xf3nica', 'Electr\xf3nica'), ('Hip-Hop', 'Hip-Hop'), ('Indie', 'Indie'), ('Jazz', 'Jazz'), ('Merenge', 'Merenge'), ('Metal', 'Metal'), ('Progresivo', 'Progresivo'), ('POP', 'POP'), ('Punk', 'Punk'), ('RAP', 'RAP'), ('Reggae', 'Reggae'), ('Reggaeton', 'Reggaeton'), ('Rock', 'Rock'), ('Rumba', 'Rumba'), ('Salsa', 'Salsa'), ('Soul', 'Soul'), ('', '----')], max_length=100)),
                ('musica', models.FileField(blank=True, null=True, upload_to='Musica/')),
                ('tiempo_registro_musica', models.DateTimeField(auto_now_add=True)),
                ('actualizado_musica', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
