# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-16 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMPlayList', '0002_auto_20170611_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='musica',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
