# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-29 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMPlayList', '0003_auto_20170616_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musica',
            name='musica',
            field=models.URLField(blank=True, default='', max_length=1000000000, null=True),
        ),
    ]
